.PHONY: all

all:
	$(MAKE) -f makefile_prototype
	$(MAKE) -f makefile_composite
	@echo "build successful"

.PHONY: clean

clean:
	$(MAKE) -f makefile_prototype clean
	$(MAKE) -f makefile_composite clean
	@echo "clean successful"
