.PHONY: all

all:
	$(MAKE) -f makefile_flyweight
	$(MAKE) -f makefile_composite
	@echo "build successful"

.PHONY: clean

clean:
	$(MAKE) -f makefile_flyweight clean
	$(MAKE) -f makefile_composite clean
	@echo "clean successful"
