.PHONY: all

all:
	$(MAKE) -f makefile_iterator
	$(MAKE) -f makefile_person
	@echo "build Iterator Pattern succssful"

.PHONY: clean

clean:
	$(MAKE) -f makefile_iterator clean
	$(MAKE) -f makefile_person clean
	@echo "clean Iterator Pattern succssful"

