.PHONY: all

all:
	$(MAKE) -f makefile_proxy
	$(MAKE) -f makefile_spacebook
	@echo "build successful"

.PHONY: clean

clean:
	$(MAKE) -f makefile_proxy clean
	$(MAKE) -f makefile_spacebook clean
	@echo "clean successful"
