.PHONY: all

all:
	$(MAKE) -f makefile_builder
	$(MAKE) -f makefile_abstract_factory
	@echo "build successful"

.PHONY: clean

clean:
	$(MAKE) -f makefile_builder clean
	$(MAKE) -f makefile_abstract_factory clean
	@echo "clean successful"
