.PHONY: all

all:
	$(MAKE) -f makefile_composite
	$(MAKE) -f makefile_test
	@echo "build successful"

.PHONY: clean

clean:
	$(MAKE) -f makefile_composite clean
	$(MAKE) -f makefile_test clean
	@echo "clean successful"
