.PHONY: all

all:
	$(MAKE) -f makefile_bridge
	$(MAKE) -f makefile_openbook
	@echo "build successful"

.PHONY: clean

clean:
	$(MAKE) -f makefile_bridge clean
	$(MAKE) -f makefile_openbook clean
	@echo "clean successful"
