.PHONY: all

all:
	$(MAKE) -f makefile_visitor
	$(MAKE) -f makefile_course
	@echo "build Visitor Pattern successful"

.PHONY: clean

clean:
	$(MAKE) -f makefile_visitor clean
	$(MAKE) -f makefile_course clean
	@echo "clean Visitor Pattern successful"

