.PHONY: all

all:
	$(MAKE) -C GettingStarted
	$(MAKE) -C WritingGoodGNULinuxSoftware
	$(MAKE) -C Process
	$(MAKE) -C Threads
	$(MAKE) -C InterprocessCommunication
	$(MAKE) -C Devices
	$(MAKE) -C TheProcFileSystem
	$(MAKE) -C LinuxSystemCalls
	$(MAKE) -C InlineAssemblyCode
	$(MAKE) -C Security
	$(MAKE) -C ASampleGNULinuxApplication
	$(MAKE) -C OtherDevelopmentTools
	$(MAKE) -C LowLevelIO
	@echo "build advanced_linux_programming successful"

.PHONY: clean

clean:
	$(MAKE) -C GettingStarted clean
	$(MAKE) -C WritingGoodGNULinuxSoftware clean
	$(MAKE) -C Process clean
	$(MAKE) -C Threads clean
	$(MAKE) -C InterprocessCommunication clean
	$(MAKE) -C Devices clean
	$(MAKE) -C TheProcFileSystem clean
	$(MAKE) -C LinuxSystemCalls clean
	$(MAKE) -C InlineAssemblyCode clean
	$(MAKE) -C Security clean
	$(MAKE) -C ASampleGNULinuxApplication clean
	$(MAKE) -C OtherDevelopmentTools clean
	$(MAKE) -C LowLevelIO clean
	@echo "clean advanced_linux_programming successful"
