.PHONY: all

all:
	$(MAKE) -C Adapter
	$(MAKE) -C Bridge 
	$(MAKE) -C Composite
	$(MAKE) -C Decorator
	$(MAKE) -C Facade
	$(MAKE) -C Flyweight
	$(MAKE) -C Prototype
	$(MAKE) -C Proxy
	$(MAKE) -C Factory
	$(MAKE) -C Singleton
	$(MAKE) -C AbstractFactory
	$(MAKE) -C Builder 
	$(MAKE) -C Strategy 
	$(MAKE) -C TemplateMethod
	$(MAKE) -C ChainOfResponsibility
	$(MAKE) -C Command
	$(MAKE) -C Iterator
	$(MAKE) -C Mediator
	$(MAKE) -C Observer
	$(MAKE) -C Visitor 
	$(MAKE) -C Interpreter
	$(MAKE) -C Memento
	$(MAKE) -C State
	@echo "build DesignPattern successful"

.PHONY: clean

clean:
	$(MAKE) -C Adapter clean
	$(MAKE) -C Bridge clean
	$(MAKE) -C Composite clean
	$(MAKE) -C Decorator clean
	$(MAKE) -C Facade clean
	$(MAKE) -C Flyweight clean
	$(MAKE) -C Prototype clean
	$(MAKE) -C Proxy clean
	$(MAKE) -C Factory clean
	$(MAKE) -C Singleton clean
	$(MAKE) -C AbstractFactory clean
	$(MAKE) -C Builder clean
	$(MAKE) -C Strategy clean
	$(MAKE) -C TemplateMethod clean
	$(MAKE) -C ChainOfResponsibility clean
	$(MAKE) -C Command clean
	$(MAKE) -C Iterator clean
	$(MAKE) -C Mediator clean
	$(MAKE) -C Observer clean
	$(MAKE) -C Visitor clean
	$(MAKE) -C Interpreter clean
	$(MAKE) -C Memento clean
	$(MAKE) -C State clean
	@echo "clean DesignPattern successful"
