.PHONY: all

all:
	$(MAKE) -f makefile_state
	$(MAKE) -f makefile_rpc
	@echo "build state pattern successful"

.PHONY: clean

clean:
	$(MAKE) -f makefile_state clean
	$(MAKE) -f makefile_rpc clean
	@echo "clean state pattern successful"
