.PHONY: all

all:
	$(MAKE) -f makefile_command
	$(MAKE) -f makefile_extend
	$(MAKE) -f makefile_plus
	$(MAKE) -f makefile_menu
	@echo "build Command Pattern successful"

.PHONY: clean

clean:
	$(MAKE) -f makefile_command clean
	$(MAKE) -f makefile_extend clean
	$(MAKE) -f makefile_plus clean
	$(MAKE) -f makefile_menu clean
	@echo "clean Command Pattern successful"
