.PHONY: all

all:
	$(MAKE) -f makefile_singleton
	$(MAKE) -f makefile_generic
	@echo "build successful"

.PHONY: clean

clean:
	$(MAKE) -f makefile_singleton clean
	$(MAKE) -f makefile_generic clean
	@echo "clean successful"

