.PHONY: all clean

all:
	make -C GettingStarted
	make -C BinarySearch
	make -C DynamicProgramming
	make -C HeapSort
	make -C StringMatching
	@echo "build introduction to algorithm successful..."

clean:
	make -C GettingStarted clean
	make -C BinarySearch clean
	make -C DynamicProgramming clean
	make -C HeapSort clean
	make -C StringMatching clean
	@echo "clean introduction to algorithm successful..."


